# ====================================
# Namespace
# ====================================
apiVersion: v1
kind: Namespace
metadata: { name: workshop }
---
# ====================================
# ConfigMap
# ====================================
apiVersion: v1
kind: ConfigMap
metadata: { name: front-config, namespace: workshop }
data:
  BANNER_TEXT: "Hello M2 IR"
---
# ====================================
# Secrets
# ====================================
apiVersion: v1
kind: Secret
metadata: { name: app-secrets, namespace: workshop }
stringData:
  DB_USER: app
  DB_PASS: changeMe123
---
# ====================================
# ClusterIssuer (cert-manager)
# ====================================
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata: { name: selfsigned }
spec:
  selfSigned: {}
---
# ====================================
# Front Deployment & Service
# ====================================
apiVersion: apps/v1
kind: Deployment
metadata: { name: front, namespace: workshop }
spec:
  replicas: 2
  selector: { matchLabels: { app: front } }
  template:
    metadata: { labels: { app: front } }
    spec:
      containers:
      - name: front
        image: nginxdemos/hello
        env:
        - name: BANNER_TEXT
          valueFrom: { configMapKeyRef: { name: front-config, key: BANNER_TEXT } }
        ports: [{ name: http, containerPort: 80 }]
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata: { name: front, namespace: workshop }
spec:
  selector: { app: front }
  ports: [{ port: 80, targetPort: http }]
---
# ====================================
# API Deployment & Service
# ====================================
apiVersion: apps/v1
kind: Deployment
metadata: { name: api, namespace: workshop }
spec:
  replicas: 2
  selector: { matchLabels: { app: api } }
  template:
    metadata: { labels: { app: api } }
    spec:
      containers:
      - name: api
        image: kennethreitz/httpbin
        ports: [{ name: http, containerPort: 80 }]
        env:
        - name: DB_USER
          valueFrom: { secretKeyRef: { name: app-secrets, key: DB_USER } }
        - name: DB_PASS
          valueFrom: { secretKeyRef: { name: app-secrets, key: DB_PASS } }
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata: { name: api, namespace: workshop }
spec:
  selector: { app: api }
  ports: [{ port: 80, targetPort: http }]
---
# ====================================
# Ingress
# ====================================
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web
  namespace: workshop
  annotations:
    cert-manager.io/cluster-issuer: selfsigned
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  tls:
  - hosts: ["workshop.local"]
    secretName: web-tls
  rules:
  - host: workshop.local
    http:
      paths:
      - path: /front(/|$)(.*)
        pathType: ImplementationSpecific
        backend: { service: { name: front, port: { number: 80 } } }
      - path: /api(/|$)(.*)
        pathType: ImplementationSpecific
        backend: { service: { name: api, port: { number: 80 } } }
---
